server:
  port: 8765

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: voyage-backend
          uri: lb://voyage-backend
          predicates:
            - Path=/**
          filters:
            - AuthenticationFilter

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka