server:
  port:
    0

spring:
  application:
    name: voyage-backend

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${DB_NAME}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql

  eureka:
    client:
      service-url:
        defaultZone: http://${EUREKA_HOST}:${EUREKA_PORT}/eureka

  rabbitmq:
    host: ${RABBIT_HOST}
    port: ${RABBIT_PORT}
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,info

  metrics:
    export:
      prometheus:
        enabled: true