spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${DB_NAME}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,info

  metrics:
    export:
      prometheus:
        enabled: true

server:
  port:
    ${APP_PORT}