server:
  port:
    0

app:
  storage-path: C:\Home\Java\voyage\photo-storage\src\main\resources\storage\

spring:
  application:
    name: photo-storage

  rabbitmq:
    host: ${RABBIT_HOST}
    port: ${RABBIT_PORT}
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST}:${EUREKA_PORT}/eureka