spring:
  application:
    name: photo-storage

  rabbitmq:
    host: ${RABBIT_HOST}
    port: ${RABBIT_PORT}
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port:
    0