server:
  port: 0

app:
  secret-key: ${SECRET_KEY}
  secret-admin: ${SECRET_ADMIN}
  token-line-cycle: ${TOKEN_LIFE_CYCLE}

spring:
  application:
    name: account-service

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${DB_NAME}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql

  eureka:
    instance:
      hostname: ${EUREKA_HOST}
    client:
      service-url:
        defaultZone: http://${EUREKA_HOST}:${EUREKA_PORT}/eureka