version: '3.1'

services:

  db:
    image: 'postgres'
    container_name: db
    ports:
      - '${POSTGRES_PORT_VOYAGE}:5432'
    environment:
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${DB_NAME_VOYAGE}

  app:
    build:
      context: ./
    container_name: app
    ports:
      - '${APP_PORT_VOYAGE}:8080'
    environment:
      - DB_NAME=${DB_NAME_VOYAGE}
      - PHOTO_SERVICE_URL=${PHOTO_SERVICE_URL}
      - POSTGRES_HOST=${POSTGRES_HOST_VOYAGE}
      - POSTGRES_PORT=${POSTGRES_PORT_DEFAULT}
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - SECRET_ADMIN=${SECRET_ADMIN_VOYAGE}
      - SECRET_KEY=${SECRET_KEY_VOYAGE}
      - APP_PORT=${APP_PORT_VOYAGE}

  rabbit:
    image: 'rabbitmq'
    container_name: rabbitmq
    ports:
      - '5672:5672'
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit
      - RABBITMQ_DEFAULT_PASS=rabbit